name: On Push to Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
  SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}

  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Deploy-Theme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@3.70.0

      - name: Theme Check
        run: |
          shopify theme check --fail-level=error

      - name: Push Theme or Create and Push Theme
        run: |
          THEME_NAME="${{ github.event.repository.name }}/${{ github.event.repository.default_branch }}"
          EXISTING_THEME=$(shopify theme list --json | jq -r --arg THEME_NAME "$THEME_NAME" '.[] | select(.name == $THEME_NAME) | .id')
          if [ -z "$EXISTING_THEME" ]; then
            echo "Theme does not exist. Creating new unpublished theme."
            shopify theme push --unpublished --theme "$THEME_NAME" --json > theme_push_output.json
          else
            echo "Theme exists. Pushing to existing theme."
            shopify theme push --theme "$THEME_NAME" --ignore config/settings_data.json --json > theme_push_output.json
          fi
      
      - name: Generate Deployment Link
        run: |
          THEME_ID=$(jq -r '.theme.id' theme_push_output.json)
          THEME_URL="https://${{ env.SHOPIFY_FLAG_STORE }}?preview_theme_id=$THEME_ID"
          echo "Theme Deployment Link: $THEME_URL"
          echo "theme_deployment_url=$THEME_URL" >> $GITHUB_ENV
      
      - name: Create GitHub Release
        run: |
          RELEASE_TAG="release-${{ github.run_number }}"
          RELEASE_NAME="Shopify Theme Deployment - Run ${{ github.run_number }}"
          gh release create "$RELEASE_TAG" \
            --title "$RELEASE_NAME" \
            --notes "Theme successfully deployed. ${{ env.theme_deployment_url }}" \
            --target main
